Fix workspace ID partitions not set correctly, causing API client error (#18)
```
singer_sdk.exceptions.FatalAPIError: 400 Client Error: Bad Request for path: /api/workspaces/%7BworkspaceId%7D/channels, content is {"timestamp":"2026-04-23T15:20:12.191775288","status":400,"error":"Bad Request","message":"Failed to convert value of type 'java.lang.String' to required type 'java.util.UUID'; nested exception is java.lang.IllegalArgumentException: Invalid UUID string: {workspaceId}","errors":[{"codes":["Type.requestParam.workspaceId"],"defaultMessage":"workspaceId should be of type java.util.UUID","objectName":"RequestParameter","field":"workspaceId","rejectedValue":"{workspaceId}","bindingFailure":true,"code":"Type.requestParam.workspaceId"}],"path":"/api/workspaces/%7BworkspaceId%7D/channels"}, headers: Date,Content-Type,Transfer-Encoding,Connection,vary,x-content-type-options,x-xss-protection,Cache-Control,pragma,expires,strict-transport-security,cf-cache-status,Nel,Report-To,Server,CF-RAY,alt-svc
```